# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"image_extensions": "01_eda.ipynb",
         "listify": "01_eda.ipynb",
         "setify": "01_eda.ipynb",
         "get_files": "01_eda.ipynb"}

modules = ["eda.py",
           "wctc_labelling.py"]

doc_url = "https://ftm624.github.io/wctc/"

git_url = "https://github.com/ftm624/wctc/tree/master/"

def custom_doc_links(name): return None
