# AUTOGENERATED! DO NOT EDIT! File to edit: 02_labelling.ipynb (unless otherwise specified).

__all__ = []

# Cell

from pathlib import WindowsPath as Path
from PIL import Image, ExifTags
import ipywidgets as widgets
from IPython.display import display

import pickle
import mimetypes
import os
import numpy as np